name: Label Non-Core Comments

on:
  issue_comment:
    types: [created]

jobs:
  label_non_core_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check if commenter is core team member
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.issue;
            const commenter = context.payload.comment.user.login;
            const coreTeam = ['abhi161']; // Replace with actual core team usernames

            // Function to add label
            async function addLabel() {
              await github.issues.addLabels({
                ...issue,
                labels: ['question'],
              });
            }

            // Function to remove label
            async function removeLabel() {
              await github.issues.removeLabel({
                ...issue,
                name: 'question',
              });
            }

            // Check if commenter is a core member
            if (!coreTeam.includes(commenter)) {
              // If non-core member, add "question" label
              await addLabel();
            } else {
              // If core member, remove "question" label
              await removeLabel();
            }
